name: release

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - workflow/release-scraped-data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            scraping started !!
      - name: Create csv file
        run: |
          python -m scripts.collect_data_technical_indicator_interval --interval 60 --limit 200 --save-path data/scraped-data.csv
      # - name: Update release body and upload files
      #   uses: meeDamian/github-release@2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     allow_override: true
      #     body: here goes the data
      #     files: >
      #       data/scraped-data.csv
      #     gzip: true
      - name: send scraped csv over telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: test-scraped-data
          document: data/*.csv
          # photo: tests/github.png