name: release

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create csv file
        run: |
          python -m scripts.collect_data --save-path data/data-april-26-1500-i2500.csv --iters 2500
      - name: Update release body and upload files
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          body: Generated on April 25 (around 8pm)
          files: >
            data/data-april-26-1500-i2500.csv
          gzip: true
