name: release

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - workflow/release-scraped-data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date)"
      - name: Test get current date
        run: |
          echo cur-date-${{ steps.date.outputs.date }}
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Scraping started for ${{ steps.date.outputs.date }}. The process may end with success / failure. 
      - name: Create csv file (scraping for 5 hrs)
        run: |
          python -m scripts.collect_data_technical_indicator_interval --interval 60 --limit 1080000
      # - name: Update release body and upload files
      #   uses: meeDamian/github-release@2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     allow_override: true
      #     body: here goes the data
      #     files: >
      #       data/scraped-data.csv
      #     gzip: true
      - name: send scraped csv over telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: successfully scraped data for ${{ steps.date.outputs.date }}
          document: scraped-data/*.csv
          # photo: tests/github.png